name: CI/CD Docker

on:
  push:
    branches: [develop]

env:
  DOCKER_IMAGE: sookyeong/modong-frontend
  NAME: modong_frontend

jobs:
  CI_CD:
    name: CI/CD
    runs-on: [self-hosted, modong-frontend]
    steps:
      - name: Deploy
        run: |
          cd ~/modong-frontend
          git fetch --all && git reset --hard origin/develop && git pull origin develop
          cp ../.env ./.env
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }}
          docker run -d -p 80:3000 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest
